// Auto-generated by scripts/build-tracks.mjs
// 307 tracks from HITSTER Denmark playlist
const TRACKS = [
  {
    "uri": "spotify:track:25cBJYmfWaAg5uhEtWQadf",
    "title": "Entertaineren - 2011 - Remaster",
    "artist": "C.V. Jørgensen",
    "year": "1977"
  },
  {
    "uri": "spotify:track:6feZhyo08N1ZJzgAnZVKqr",
    "title": "Arh Dér !",
    "artist": "Mc Einar",
    "year": "1989"
  },
  {
    "uri": "spotify:track:4RvWPyQ5RL0ao9LPZeSouE",
    "title": "Everybody Wants To Rule The World",
    "artist": "Tears For Fears",
    "year": "1985"
  },
  {
    "uri": "spotify:track:45Szkclj1lt4ubm7RFK68t",
    "title": "Runaway",
    "artist": "Del Shannon",
    "year": "1961"
  },
  {
    "uri": "spotify:track:09IStsImFySgyp0pIQdqAc",
    "title": "The Middle",
    "artist": "Zedd, Maren Morris, Grey",
    "year": "2018"
  },
  {
    "uri": "spotify:track:2JzZzZUQj3Qff7wapcbKjc",
    "title": "See You Again (feat. Charlie Puth)",
    "artist": "Wiz Khalifa, Charlie Puth",
    "year": "2015"
  },
  {
    "uri": "spotify:track:5B0tUbgCTcvsZgIPjpNKtE",
    "title": "Dragostea Din Tei - Original Romanian Version",
    "artist": "O-Zone",
    "year": "2004"
  },
  {
    "uri": "spotify:track:0OTO8ZF2YqFQVw9hnZylTd",
    "title": "What Is Love - 7\" Mix",
    "artist": "Haddaway",
    "year": "1993"
  },
  {
    "uri": "spotify:track:5iVIQLVaxtgTmRAEpUkrXh",
    "title": "Let Your Fingers Do The Walking - Remastered",
    "artist": "Sort Sol",
    "year": "1993"
  },
  {
    "uri": "spotify:track:5KqldkCunQ2rWxruMEtGh0",
    "title": "The Gambler",
    "artist": "Kenny Rogers",
    "year": "1978"
  },
  {
    "uri": "spotify:track:1UzofFX5AkfTDnwjcBkM4J",
    "title": "Whiskey in the Jar",
    "artist": "The Dubliners",
    "year": "2002"
  },
  {
    "uri": "spotify:track:70LcF31zb1H0PyJoS1Sx1r",
    "title": "Creep",
    "artist": "Radiohead",
    "year": "1993"
  },
  {
    "uri": "spotify:track:5JGEAz15LkPoOtFHttDtVs",
    "title": "With Or Without You - Remastered 2007",
    "artist": "U2",
    "year": "1987"
  },
  {
    "uri": "spotify:track:1CtAzw53AIXKjAemxy4b1j",
    "title": "Beds Are Burning - Remastered",
    "artist": "Midnight Oil",
    "year": "1987"
  },
  {
    "uri": "spotify:track:1DgZBCT9XFZOY610rLyHOE",
    "title": "Flying",
    "artist": "Nice Little Penguins",
    "year": "1994"
  },
  {
    "uri": "spotify:track:05tlUh0E6IFks9sCQguQKN",
    "title": "Rockstar - 2020 Remaster",
    "artist": "Nickelback",
    "year": "2005"
  },
  {
    "uri": "spotify:track:1eyq8cjUQ2daFthW2PC2GM",
    "title": "Glory of Love",
    "artist": "Peter Cetera",
    "year": "1986"
  },
  {
    "uri": "spotify:track:4Zc9x0dWu7KSZtWtRsYKxX",
    "title": "Krumme's Sang",
    "artist": "Laus Høybye, Krummerne",
    "year": "1992"
  },
  {
    "uri": "spotify:track:0qc4QlcCxVTGyShurEv1UU",
    "title": "Post Malone (feat. RANI)",
    "artist": "Sam Feldt, RANI",
    "year": "2019"
  },
  {
    "uri": "spotify:track:3Veqbiz7pMTDrnpqXcCBJb",
    "title": "Når en sailor går i land",
    "artist": "Otto Brandenburg",
    "year": "1996"
  },
  {
    "uri": "spotify:track:5TjDwWPZ5vScUEG0NeRtuB",
    "title": "Op",
    "artist": "Claus Hempler",
    "year": "2019"
  },
  {
    "uri": "spotify:track:3AeicLnm55RqcXGBKYQolM",
    "title": "King",
    "artist": "Olly Alexander (Years & Years)",
    "year": "2015"
  },
  {
    "uri": "spotify:track:0HJTHmEqrKSh3i3V6WWln8",
    "title": "Mandalay - Dansk version; 2005 - Remaster",
    "artist": "Four Jacks",
    "year": "2005"
  },
  {
    "uri": "spotify:track:0nrRP2bk19rLc0orkWPQk2",
    "title": "Wake Me Up",
    "artist": "Avicii",
    "year": "2013"
  },
  {
    "uri": "spotify:track:1vXB0If9PfpM5mcTShrQQU",
    "title": "Coco Jamboo",
    "artist": "Mr. President",
    "year": "1996"
  },
  {
    "uri": "spotify:track:3QHONiXGMGU3z68mQInncF",
    "title": "I'll Be Missing You (feat. Faith Evans, 112)",
    "artist": "Diddy, Faith Evans, 112",
    "year": "2004"
  },
  {
    "uri": "spotify:track:7DnAm9FOTWE3cUvso43HhI",
    "title": "Sweet but Psycho",
    "artist": "Ava Max",
    "year": "2020"
  },
  {
    "uri": "spotify:track:3fH4KjXFYMmljxrcGrbPj9",
    "title": "Don't You (Forget About Me)",
    "artist": "Simple Minds",
    "year": "1985"
  },
  {
    "uri": "spotify:track:4P0HGIhWV7dm2KzlZUEHZJ",
    "title": "De skal have baghjul nede i touren",
    "artist": "Drengene Fra Angora",
    "year": "2005"
  },
  {
    "uri": "spotify:track:3mRM4NM8iO7UBqrSigCQFH",
    "title": "Stayin' Alive - From \"Saturday Night Fever\" Soundtrack",
    "artist": "Bee Gees",
    "year": "1979"
  },
  {
    "uri": "spotify:track:0GWGZA5mxo9nHuSyrj70uo",
    "title": "When Love Takes Over (feat. Kelly Rowland)",
    "artist": "David Guetta, Kelly Rowland",
    "year": "2010"
  },
  {
    "uri": "spotify:track:1hvKYV2SkmX1D2AeRCDxLH",
    "title": "Bang Bang (My Baby Shot Me Down)",
    "artist": "Nancy Sinatra",
    "year": "2024"
  },
  {
    "uri": "spotify:track:0B52e8kJrbBzUfTMP1O4Ss",
    "title": "Papirsklip",
    "artist": "Kim Larsen",
    "year": "1983"
  },
  {
    "uri": "spotify:track:4HIi6uNZhGb9BXLGlXaADk",
    "title": "Gem Et Lille Smil Til Det Bli'r Gråvejr",
    "artist": "Gustav Winckler",
    "year": "2015"
  },
  {
    "uri": "spotify:track:1OiHhFchzvzhLGxCpLJOyP",
    "title": "Dear Little Mother",
    "artist": "The Savage Rose",
    "year": "2010"
  },
  {
    "uri": "spotify:track:1Qrdlkgg9I4J7r3P4kZNwr",
    "title": "Missing You",
    "artist": "John Waite",
    "year": "1984"
  },
  {
    "uri": "spotify:track:57bgtoPSgt236HzfBOd8kj",
    "title": "Thunderstruck",
    "artist": "AC/DC",
    "year": "1990"
  },
  {
    "uri": "spotify:track:1JLn8RhQzHz3qDqsChcmBl",
    "title": "I Want to Know What Love Is - 1999 Remaster",
    "artist": "Foreigner",
    "year": "1984"
  },
  {
    "uri": "spotify:track:7CNCYcc5D7ViFS4fsWe3B6",
    "title": "Det Er Mig Der Står Herude Og Banker På",
    "artist": "Thomas Helmig",
    "year": "1988"
  },
  {
    "uri": "spotify:track:22ureEREoYmAIwxm8ZBSIK",
    "title": "Kun Med Dig",
    "artist": "Malte Ebert",
    "year": "2022"
  },
  {
    "uri": "spotify:track:2fXKyAyPrEa24c6PJyqznF",
    "title": "Common People - Full Length Version",
    "artist": "Pulp",
    "year": "1995"
  },
  {
    "uri": "spotify:track:0eifvmNPHWaSh4IKNR4Xva",
    "title": "To Be With You - 2021 Remastered",
    "artist": "Mr. Big",
    "year": "1991"
  },
  {
    "uri": "spotify:track:18DfMhEx4ddoreHrvZDF6Q",
    "title": "The Power of Love",
    "artist": "Jennifer Rush",
    "year": "1995"
  },
  {
    "uri": "spotify:track:3PECLp2lSHSZK1B0hdh6cs",
    "title": "Jeg vil i seng med de fleste",
    "artist": "Det Brune Punktum",
    "year": "1999"
  },
  {
    "uri": "spotify:track:7jGzYUZ2Bgg8BDfYlQRfn8",
    "title": "Wild Thing",
    "artist": "The Troggs",
    "year": "1966"
  },
  {
    "uri": "spotify:track:6brl7bwOHmGFkNw3MBqssT",
    "title": "So Sick",
    "artist": "Ne-Yo",
    "year": "2006"
  },
  {
    "uri": "spotify:track:6c1kzTI5n0qskewueIsvtJ",
    "title": "Så Længe Jeg Lever",
    "artist": "John Mogensen",
    "year": "1973"
  },
  {
    "uri": "spotify:track:6EXi6ZqTITKGtVBKqbphjL",
    "title": "Porcelain",
    "artist": "Moby",
    "year": "1999"
  },
  {
    "uri": "spotify:track:36rXHqN7D1ETFhyKXXKs4w",
    "title": "Gonna Make You Sweat (Everybody Dance Now) (feat. Freedom Williams)",
    "artist": "C & C Music Factory, Freedom Williams",
    "year": "1990"
  },
  {
    "uri": "spotify:track:5EwP9NvAJHsWVqVguSx5IM",
    "title": "Igen & Igen &",
    "artist": "Nephew",
    "year": "2006"
  },
  {
    "uri": "spotify:track:77Nw4E8ji9K2vG23rQikBc",
    "title": "When All The Saints Come Marching In (Take 1)",
    "artist": "Paramount Jubilee Singers",
    "year": "2005"
  },
  {
    "uri": "spotify:track:7vyt6zsNQ1Ni1Q2k7NxwYd",
    "title": "Favourite Lover",
    "artist": "eee gee",
    "year": "2022"
  },
  {
    "uri": "spotify:track:5JVbvCHX10U2pLa5DEqGav",
    "title": "Safe and Sound",
    "artist": "Capital Cities",
    "year": "2013"
  },
  {
    "uri": "spotify:track:1pTGc8pwyo6xtgXBKCBcFn",
    "title": "Woman in Love",
    "artist": "Barbra Streisand",
    "year": "1980"
  },
  {
    "uri": "spotify:track:0nnScCJyGhTLmc5ozc3ebt",
    "title": "Jeg sætter min hat som jeg vil",
    "artist": "Daimi",
    "year": "1993"
  },
  {
    "uri": "spotify:track:1RGL48ceSL1dAgzCgmZTdj",
    "title": "De Første Kærester På Månen",
    "artist": "TV-2",
    "year": "2005"
  },
  {
    "uri": "spotify:track:7kyMLaXepcGHIrsLqoiTB8",
    "title": "Ooh Aah...Just a Little Bit - Motiv8 Radio Edit",
    "artist": "Gina G, Motiv8",
    "year": "1997"
  },
  {
    "uri": "spotify:track:5Nm9ERjJZ5oyfXZTECKmRt",
    "title": "Stay With Me",
    "artist": "Sam Smith",
    "year": "2014"
  },
  {
    "uri": "spotify:track:5AgCO3dc2kuSicCsw09YCA",
    "title": "The Rockafeller Skank",
    "artist": "Fatboy Slim",
    "year": "1998"
  },
  {
    "uri": "spotify:track:1eOJAiCKFuMda0fPRvjcuc",
    "title": "Hold My Hand",
    "artist": "Jess Glynne",
    "year": "2015"
  },
  {
    "uri": "spotify:track:1k1Bqnv2R0uJXQN4u6LKYt",
    "title": "Ain't No Sunshine",
    "artist": "Bill Withers",
    "year": "1971"
  },
  {
    "uri": "spotify:track:4NRQwaks9r58tTDvr4iEyv",
    "title": "In the Midnight Hour",
    "artist": "Wilson Pickett",
    "year": "1965"
  },
  {
    "uri": "spotify:track:0qi4b1l0eT3jpzeNHeFXDT",
    "title": "Just Can't Get Enough",
    "artist": "Depeche Mode",
    "year": "1981"
  },
  {
    "uri": "spotify:track:3SnGymj6ijE2iuUfWxLo1q",
    "title": "I'm Coming Out",
    "artist": "Diana Ross",
    "year": "1980"
  },
  {
    "uri": "spotify:track:0fYVliAYKHuPmECRs1pbRf",
    "title": "Renegades",
    "artist": "X Ambassadors",
    "year": "2015"
  },
  {
    "uri": "spotify:track:33frkbGSt6bbfj2Nqo9i1p",
    "title": "Smuk som et stjerneskud",
    "artist": "Brødrene Olsen",
    "year": "2000"
  },
  {
    "uri": "spotify:track:1oTHteQbmJw15rPxPVXUTv",
    "title": "Insane in the Brain",
    "artist": "Cypress Hill",
    "year": "1993"
  },
  {
    "uri": "spotify:track:4BggEwLhGfrbrl7JBhC8EC",
    "title": "Butterfly",
    "artist": "Crazy Town",
    "year": "2000"
  },
  {
    "uri": "spotify:track:4POgt5ayni68MeLqclubcC",
    "title": "Red Red Wine",
    "artist": "UB40",
    "year": "1987"
  },
  {
    "uri": "spotify:track:2LEF1A8DOZ9wRYikWgVlZ8",
    "title": "Good Feeling",
    "artist": "Flo Rida",
    "year": "2012"
  },
  {
    "uri": "spotify:track:7mitXLIMCflkhZiD34uEQI",
    "title": "Party Rock Anthem",
    "artist": "LMFAO, Lauren Bennett, GoonRock",
    "year": "2011"
  },
  {
    "uri": "spotify:track:3MrWxJaD2AT0W9DjWF64Vm",
    "title": "Come On Eileen",
    "artist": "Dexys Midnight Runners",
    "year": "1982"
  },
  {
    "uri": "spotify:track:6er2fnqYjKvkOfUICSf28W",
    "title": "Bornholm, Bornholm, Bornholm",
    "artist": "Ib Mossin, Lille Per",
    "year": "1959"
  },
  {
    "uri": "spotify:track:6qUEOWqOzu1rLPUPQ1ECpx",
    "title": "Walk This Way (feat. Aerosmith)",
    "artist": "Run–D.M.C., Aerosmith",
    "year": "1986"
  },
  {
    "uri": "spotify:track:78TVWUTtCC4WAhi0SRPxQK",
    "title": "O Sole Mio",
    "artist": "Enrico Caruso",
    "year": "2011"
  },
  {
    "uri": "spotify:track:6UelLqGlWMcVH1E5c4H7lY",
    "title": "Watermelon Sugar",
    "artist": "Harry Styles",
    "year": "2019"
  },
  {
    "uri": "spotify:track:3Nf8oGn1okobzjDcFCvT6n",
    "title": "I'll Stand by You",
    "artist": "Pretenders",
    "year": "1994"
  },
  {
    "uri": "spotify:track:3iMLRCGHLQ135LtMjKLkO8",
    "title": "Heartbreaker",
    "artist": "Dionne Warwick",
    "year": "1982"
  },
  {
    "uri": "spotify:track:10I09MLZCY4pK37XxAfkw0",
    "title": "True - 2003 Remaster",
    "artist": "Spandau Ballet",
    "year": "1983"
  },
  {
    "uri": "spotify:track:4ummJ3eSCWJMbxJHvNojyt",
    "title": "Herfra Hvor Vi Står",
    "artist": "Skousen Og Ingemann",
    "year": "1971"
  },
  {
    "uri": "spotify:track:0BxfFnk0YzONqvmrkO0QrB",
    "title": "Don't Cha",
    "artist": "The Pussycat Dolls, Busta Rhymes",
    "year": "2005"
  },
  {
    "uri": "spotify:track:0nrC6N6HyEZu0TbZ4yA7ag",
    "title": "Glemmer du - track version",
    "artist": "Liva Weel",
    "year": "1951"
  },
  {
    "uri": "spotify:track:0wSx9zG1fSKLIpFlbWg3Y9",
    "title": "Nana",
    "artist": "Sebastian",
    "year": "1987"
  },
  {
    "uri": "spotify:track:1rqqCSm0Qe4I9rUvWncaom",
    "title": "High Hopes",
    "artist": "Panic! At The Disco",
    "year": "2018"
  },
  {
    "uri": "spotify:track:2T3jgoAMbBXiMMD8pSc6QL",
    "title": "This Is The Life",
    "artist": "Amy Macdonald",
    "year": "2007"
  },
  {
    "uri": "spotify:track:28UMiBhn383n9S7GL4tsxD",
    "title": "Because You Loved Me (Theme from \"Up Close and Personal\")",
    "artist": "Céline Dion",
    "year": "1996"
  },
  {
    "uri": "spotify:track:73niCPzZkDLz33Ei7ji243",
    "title": "Please Don't Lie",
    "artist": "Hugo Helmig",
    "year": "2019"
  },
  {
    "uri": "spotify:track:1xNmF1Uep5OGutizZSbKvd",
    "title": "One Of Us",
    "artist": "Joan Osborne",
    "year": "1995"
  },
  {
    "uri": "spotify:track:3Nj3yIZlUQzdSuyWyQWji8",
    "title": "Der kommer altid en sporvogn og en pige til",
    "artist": "Dirch Passer, Ove Sprogø",
    "year": "2008"
  },
  {
    "uri": "spotify:track:05fHQeRbCSjKVS6z0WbQKJ",
    "title": "Every Time You Go Away - Radio Edit",
    "artist": "Paul Young",
    "year": "1991"
  },
  {
    "uri": "spotify:track:3QRM0qZB7oMYavveH0iEqx",
    "title": "Here Comes the Hotstepper - Heartical Mix",
    "artist": "iNi Kamoze, Salaam Remi",
    "year": "1994"
  },
  {
    "uri": "spotify:track:47f5VH4gBRdqkMtFctiveF",
    "title": "Danse i Måneskin",
    "artist": "Trine & Moonlighters, Trine Dyrholm",
    "year": "1987"
  },
  {
    "uri": "spotify:track:4pW3aTX3kAmOaPJfc9UM12",
    "title": "Express Yourself",
    "artist": "Charles Wright & The Watts 103rd Street Rhythm Band",
    "year": "1970"
  },
  {
    "uri": "spotify:track:1Hh5gDiXZGhtKfHzJYYhSJ",
    "title": "Give It Up",
    "artist": "Cut 'N' Move",
    "year": "1993"
  },
  {
    "uri": "spotify:track:3XKIUb7HzIF1Vu9usunMzc",
    "title": "Maria Maria (feat. The Product G&B)",
    "artist": "Santana, The Product G&B",
    "year": "1999"
  },
  {
    "uri": "spotify:track:1DIXPcTDzTj8ZMHt3PDt8p",
    "title": "Gangsta's Paradise",
    "artist": "Coolio, L.V.",
    "year": "1995"
  },
  {
    "uri": "spotify:track:1NDxZ7cFAo481dtYWdrUnR",
    "title": "Pretty Girl - Cheat Codes X CADE Remix",
    "artist": "Maggie Lindemann, Cheat Codes, CADE",
    "year": "2017"
  },
  {
    "uri": "spotify:track:5XVjNRubJUW0iPhhSWpLCj",
    "title": "Better Off Alone",
    "artist": "Alice Deejay",
    "year": "2000"
  },
  {
    "uri": "spotify:track:3zBhihYUHBmGd2bcQIobrF",
    "title": "(Sittin' On) the Dock of the Bay",
    "artist": "Otis Redding",
    "year": "1968"
  },
  {
    "uri": "spotify:track:195u5gKS4I6FZle04gw2aR",
    "title": "Ayo Technology",
    "artist": "Milow",
    "year": "2009"
  },
  {
    "uri": "spotify:track:3MrRksHupTVEQ7YbA0FsZK",
    "title": "The Final Countdown",
    "artist": "Europe",
    "year": "1986"
  },
  {
    "uri": "spotify:track:2rObT05oR8VLpd43sgURiM",
    "title": "She Cries",
    "artist": "C21",
    "year": "2003"
  },
  {
    "uri": "spotify:track:5Klo65Y9uouLjNVDV3pqh7",
    "title": "Go West - 2003 Remaster",
    "artist": "Pet Shop Boys",
    "year": "2003"
  },
  {
    "uri": "spotify:track:4fHDlIntTsRGSyTg5UYZYC",
    "title": "Banana Boat (Day-O)",
    "artist": "Harry Belafonte",
    "year": "1956"
  },
  {
    "uri": "spotify:track:1VaKAul2PvFy383BHIhUAn",
    "title": "Hvor ska' vi sove i nat? - 2009 - Remaster",
    "artist": "Laban",
    "year": "1982"
  },
  {
    "uri": "spotify:track:6FUAlX42Hm3FHoU4EgiQ3F",
    "title": "Jeg savner min blå cykel",
    "artist": "Ibens",
    "year": "1997"
  },
  {
    "uri": "spotify:track:3n8Yh1mpyi15R4mNnHXktL",
    "title": "Matador",
    "artist": "Bent Fabricius-Bjerre",
    "year": "2001"
  },
  {
    "uri": "spotify:track:2xB2iRyV17r7D4FGZLlieO",
    "title": "Mr. Swing King",
    "artist": "GNAGS",
    "year": "1989"
  },
  {
    "uri": "spotify:track:3aPlQWU07jGgyHaBHVS5TS",
    "title": "Fever",
    "artist": "Peggy Lee",
    "year": "1958"
  },
  {
    "uri": "spotify:track:5uES1C2NgkdrNHiCwf9jRr",
    "title": "Baby Love",
    "artist": "The Supremes",
    "year": "1964"
  },
  {
    "uri": "spotify:track:0cVyQfDyRnMJ0V3rjjdlU3",
    "title": "Lil Boo Thang",
    "artist": "Paul Russell",
    "year": "2023"
  },
  {
    "uri": "spotify:track:6in24bEdgm8kJqd7eGR3q9",
    "title": "Kommet For At Danse",
    "artist": "Specktors",
    "year": "2020"
  },
  {
    "uri": "spotify:track:7tsPUms7n1f7k4VWrBXIki",
    "title": "Skibet Skal Sejle I Nat",
    "artist": "Gustav Winckler, Birthe Wilke",
    "year": "1979"
  },
  {
    "uri": "spotify:track:6JIC3hbC28JZKZ8AlAqX8h",
    "title": "Cold Heart - PNAU Remix",
    "artist": "Elton John, Dua Lipa, PNAU",
    "year": "2021"
  },
  {
    "uri": "spotify:track:2brA80LHyPS3wdiqiw2n6V",
    "title": "Heksedansen",
    "artist": "Raquel Rastenni",
    "year": "2000"
  },
  {
    "uri": "spotify:track:3EDS89HeAhHiZKlljciK0a",
    "title": "Push The Button",
    "artist": "Sugababes",
    "year": "2005"
  },
  {
    "uri": "spotify:track:2fARVTvENb670WbTS57RqU",
    "title": "Hang with Me",
    "artist": "Robyn",
    "year": "2010"
  },
  {
    "uri": "spotify:track:1jcPcDu2YawPfLhwjYnqK2",
    "title": "Everybody's Talkin' - From \"Midnight Cowboy\"",
    "artist": "Harry Nilsson",
    "year": "1968"
  },
  {
    "uri": "spotify:track:5b7OgznPJJr1vHNYGyvxau",
    "title": "Fly Me To The Moon (In Other Words)",
    "artist": "Frank Sinatra, Count Basie",
    "year": "1962"
  },
  {
    "uri": "spotify:track:3R6dPfF2yBO8mHySW1XDAa",
    "title": "Solo Dance",
    "artist": "Martin Jensen",
    "year": "2016"
  },
  {
    "uri": "spotify:track:4vxvOAun0m1rbKKoVLC6zG",
    "title": "The Balcony",
    "artist": "The Rumour Said Fire",
    "year": "2009"
  },
  {
    "uri": "spotify:track:3evG0BIqEFMMP7lVJh1cSf",
    "title": "Don't Let Me Down - Remastered 2009",
    "artist": "The Beatles",
    "year": "1973"
  },
  {
    "uri": "spotify:track:0DwClY2t9YAWHBROMIgrXb",
    "title": "Ho Hey",
    "artist": "The Lumineers",
    "year": "2012"
  },
  {
    "uri": "spotify:track:6o4T3KvB4Qyq2qlmyqMwYw",
    "title": "Scandinavian Shuffle",
    "artist": "The Swe-Danes",
    "year": "1960"
  },
  {
    "uri": "spotify:track:5i64qUf9pDvBeGefmitLQ8",
    "title": "Sømand af Verden",
    "artist": "Dodo & the Dodos",
    "year": "2018"
  },
  {
    "uri": "spotify:track:74FD6mxhAIzgUEGb4dAF3r",
    "title": "So Far",
    "artist": "Superheroes",
    "year": "2001"
  },
  {
    "uri": "spotify:track:63xdwScd1Ai1GigAwQxE8y",
    "title": "Let's Stay Together",
    "artist": "Al Green",
    "year": "1972"
  },
  {
    "uri": "spotify:track:3WkibOpDF7cQ5xntM1epyf",
    "title": "It Wasn't Me",
    "artist": "Shaggy, Rik Rok",
    "year": "2000"
  },
  {
    "uri": "spotify:track:5Mqak2PQs4oExjYHiFoStB",
    "title": "Mandags-Stævnemøde",
    "artist": "Ray Dee Ohh",
    "year": "1989"
  },
  {
    "uri": "spotify:track:0xpBr84T3FTm9j4D1MdPtk",
    "title": "Invisible Touch - 2007 Remaster",
    "artist": "Genesis",
    "year": "1986"
  },
  {
    "uri": "spotify:track:0eqH0ALoDQevq59YcQ53KE",
    "title": "Hollaback Girl",
    "artist": "Gwen Stefani",
    "year": "2004"
  },
  {
    "uri": "spotify:track:5rb9QrpfcKFHM1EUbSIurX",
    "title": "Yeah! (feat. Lil Jon & Ludacris)",
    "artist": "USHER, Lil Jon, Ludacris",
    "year": "2004"
  },
  {
    "uri": "spotify:track:1nXTM2CVdaoCySSD5kgt3J",
    "title": "Sweat (A La La La La Long)",
    "artist": "Inner Circle",
    "year": "1992"
  },
  {
    "uri": "spotify:track:4JVzugKZLHSNeyHJaeeVn5",
    "title": "Sådan Nogen Som Os",
    "artist": "Poul Krebs",
    "year": "1995"
  },
  {
    "uri": "spotify:track:3qaQrPCyoM5qGGrsgkS14F",
    "title": "Bonsoir Madame",
    "artist": "Big Fat Snake",
    "year": "1997"
  },
  {
    "uri": "spotify:track:598JrQyHZ5oviov9RFjsM8",
    "title": "Kom Tilbage Nu",
    "artist": "Danseorkestret",
    "year": "2014"
  },
  {
    "uri": "spotify:track:6BjG4NirMgJfC6QAvbfBNG",
    "title": "Substitution (feat. Julian Perretta)",
    "artist": "Purple Disco Machine, Kungs, Julian Perretta",
    "year": "2024"
  },
  {
    "uri": "spotify:track:1J2n4bAqt4KIvM9rYSByfE",
    "title": "Don't Know Much About Love",
    "artist": "Hanne Boel",
    "year": "1992"
  },
  {
    "uri": "spotify:track:4iArHiBejqLpJBKzok0EC3",
    "title": "Kald det kærlighed",
    "artist": "Lars Lilholt Band",
    "year": "1996"
  },
  {
    "uri": "spotify:track:7JKEA8xYDoFp4q0QBW2PGg",
    "title": "Shackles (Praise You)",
    "artist": "Mary Mary",
    "year": "2000"
  },
  {
    "uri": "spotify:track:7qtAgn9mwxygsPOsUDVRRt",
    "title": "Survivor",
    "artist": "Destiny's Child",
    "year": "2001"
  },
  {
    "uri": "spotify:track:34lKSVnaKW8T1EmGe44LKp",
    "title": "Don't Look For Love",
    "artist": "Shirley, Jonas Winge Leisner",
    "year": "1999"
  },
  {
    "uri": "spotify:track:5L8ta4ECl5zeA6bGqY7G38",
    "title": "Sing, Sing, Sing",
    "artist": "Benny Goodman",
    "year": "2007"
  },
  {
    "uri": "spotify:track:583xVl0Sbj93uU4ceixgU8",
    "title": "I'm Outta Love - Radio Edit",
    "artist": "Anastacia",
    "year": "1999"
  },
  {
    "uri": "spotify:track:7utoClKnLShFg6u6dZ20gp",
    "title": "Breaking Up Is Hard to Do",
    "artist": "Neil Sedaka",
    "year": "2003"
  },
  {
    "uri": "spotify:track:66iKqUazBbTlAEjcZrpDkD",
    "title": "What A Diff'rence A Day Made",
    "artist": "Dinah Washington",
    "year": "1959"
  },
  {
    "uri": "spotify:track:2Ryb4kO2Pl7YInhuOUecda",
    "title": "Ding Dong",
    "artist": "Tessa",
    "year": "2023"
  },
  {
    "uri": "spotify:track:2plbrEY59IikOBgBGLjaoe",
    "title": "Die With A Smile",
    "artist": "Lady Gaga, Bruno Mars",
    "year": "2024"
  },
  {
    "uri": "spotify:track:4XPWKmy05Rcff6TLHNoNF8",
    "title": "Ghost",
    "artist": "Ella Henderson",
    "year": "2014"
  },
  {
    "uri": "spotify:track:2qT1uLXPVPzGgFOx4jtEuo",
    "title": "no tears left to cry",
    "artist": "Ariana Grande",
    "year": "2018"
  },
  {
    "uri": "spotify:track:2hNf1rawV2XAZ6Jld2Fxwf",
    "title": "Always On Time",
    "artist": "Ja Rule, Ashanti",
    "year": "2001"
  },
  {
    "uri": "spotify:track:0b9djfiuDIMw1zKH6gV74g",
    "title": "Somebody Like You",
    "artist": "Keith Urban",
    "year": "2002"
  },
  {
    "uri": "spotify:track:4gMgiXfqyzZLMhsksGmbQV",
    "title": "Another Brick in the Wall, Pt. 2",
    "artist": "Pink Floyd",
    "year": "1979"
  },
  {
    "uri": "spotify:track:07q0QVgO56EorrSGHC48y3",
    "title": "I Was Made For Lovin' You",
    "artist": "KISS",
    "year": "1979"
  },
  {
    "uri": "spotify:track:3rmo8F54jFF8OgYsqTxm5d",
    "title": "Bad Habits",
    "artist": "Ed Sheeran",
    "year": "2021"
  },
  {
    "uri": "spotify:track:3N3I5NPzuv8ZEUnXWEU0Mu",
    "title": "Den første gang",
    "artist": "Innocent Blood",
    "year": "1999"
  },
  {
    "uri": "spotify:track:2qrxwBsuhtAopI7inJxW6u",
    "title": "Lyse Nætter",
    "artist": "Alberte Winding",
    "year": "1991"
  },
  {
    "uri": "spotify:track:6HSXNV0b4M4cLJ7ljgVVeh",
    "title": "Knockin' On Heaven's Door",
    "artist": "Bob Dylan",
    "year": "1973"
  },
  {
    "uri": "spotify:track:1MntHPLU1T7a9W4tojbg8g",
    "title": "Mercedes Benz",
    "artist": "Janis Joplin",
    "year": "1971"
  },
  {
    "uri": "spotify:track:6iXQrhhgBisdfvS34EMTZ3",
    "title": "Mandy",
    "artist": "Barry Manilow",
    "year": "1974"
  },
  {
    "uri": "spotify:track:58z9sfHe9s9zTvYGKehCWM",
    "title": "Here I Go Again - 1987 Version / 2018 Remaster",
    "artist": "Whitesnake",
    "year": "1987"
  },
  {
    "uri": "spotify:track:5MoDQWMDMaAGDEiWsJfeCi",
    "title": "Eternal Flame",
    "artist": "The Bangles, Susanna Hoffs",
    "year": "2004"
  },
  {
    "uri": "spotify:track:37ZJ0p5Jm13JPevGcx4SkF",
    "title": "Livin' On A Prayer",
    "artist": "Bon Jovi",
    "year": "1986"
  },
  {
    "uri": "spotify:track:5XcZRgJv3zMhTqCyESjQrF",
    "title": "Poison",
    "artist": "Alice Cooper",
    "year": "1989"
  },
  {
    "uri": "spotify:track:20LRRF2F5yWxADmN3dLlkP",
    "title": "Ulven Peter (Lil' Red Riding Hood)",
    "artist": "Peter Belli",
    "year": "1999"
  },
  {
    "uri": "spotify:track:5D5Iwi9xI64mqdQOU9lTui",
    "title": "Fuck You",
    "artist": "CeeLo Green",
    "year": "2010"
  },
  {
    "uri": "spotify:track:27AHAtAirQapVldIm4c9ZX",
    "title": "Jump",
    "artist": "Kris Kross",
    "year": "1992"
  },
  {
    "uri": "spotify:track:3UBItNVbFQiVC5hBQlBvnr",
    "title": "Your Woman",
    "artist": "White Town",
    "year": "1997"
  },
  {
    "uri": "spotify:track:5Hroj5K7vLpIG4FNCRIjbP",
    "title": "Best Day Of My Life",
    "artist": "American Authors",
    "year": "2014"
  },
  {
    "uri": "spotify:track:782lNGn2rEHVn8JomdtRA7",
    "title": "Barbra Streisand - Radio Edit",
    "artist": "Duck Sauce, A-Trak, Armand Van Helden",
    "year": "2010"
  },
  {
    "uri": "spotify:track:5mFQCdbvuzVATC7tP7XsPp",
    "title": "Rhythm Is a Dancer - 7\" Edit",
    "artist": "SNAP!",
    "year": "1992"
  },
  {
    "uri": "spotify:track:02ymWg1NUOrvrESz6Dvtrx",
    "title": "Jeg ved det godt",
    "artist": "Rugsted & Kreutzfeldt",
    "year": "1979"
  },
  {
    "uri": "spotify:track:0qOnSQQF0yzuPWsXrQ9paz",
    "title": "Stereo Hearts (feat. Adam Levine)",
    "artist": "Gym Class Heroes, Adam Levine",
    "year": "2011"
  },
  {
    "uri": "spotify:track:4u7EnebtmKWzUH433cf5Qv",
    "title": "Bohemian Rhapsody - Remastered 2011",
    "artist": "Queen",
    "year": "1975"
  },
  {
    "uri": "spotify:track:0UOxp1BpnD8uPQMKU4wKjz",
    "title": "I Shot The Sheriff",
    "artist": "Eric Clapton",
    "year": "1974"
  },
  {
    "uri": "spotify:track:0wHFktze2PHC5jDt3B17DC",
    "title": "First Class",
    "artist": "Jack Harlow",
    "year": "2022"
  },
  {
    "uri": "spotify:track:2m1hi0nfMR9vdGC8UcrnwU",
    "title": "All The Small Things",
    "artist": "blink-182",
    "year": "1999"
  },
  {
    "uri": "spotify:track:6ECp64rv50XVz93WvxXMGF",
    "title": "This Love",
    "artist": "Maroon 5",
    "year": "2002"
  },
  {
    "uri": "spotify:track:04aAxqtGp5pv12UXAg4pkq",
    "title": "Centuries",
    "artist": "Fall Out Boy",
    "year": "2015"
  },
  {
    "uri": "spotify:track:5kWcIgj5CszKQBB0Lg7sGY",
    "title": "Let Her Go",
    "artist": "Passenger",
    "year": "2013"
  },
  {
    "uri": "spotify:track:4FRs21rqzPUJxOgLg9eJpb",
    "title": "Spændt Op Til Lir",
    "artist": "Den Gale Pose",
    "year": "1998"
  },
  {
    "uri": "spotify:track:2539KcLV6WkgGdNkkrpGMi",
    "title": "Natteravn",
    "artist": "Rasmus Seebach",
    "year": "2009"
  },
  {
    "uri": "spotify:track:41Fflg7qHiVOD6dEPvsCzO",
    "title": "Worth It (feat. Kid Ink)",
    "artist": "Fifth Harmony, Kid Ink",
    "year": "2015"
  },
  {
    "uri": "spotify:track:6mhw2fEPH4fMF0wolNm96e",
    "title": "Macarena",
    "artist": "Los Del Rio",
    "year": "2002"
  },
  {
    "uri": "spotify:track:2CdS3DRqWR5LAhy4hM5X9W",
    "title": "Laid",
    "artist": "James",
    "year": "1993"
  },
  {
    "uri": "spotify:track:5AKQ1JHezaXDmN5SyMSpEr",
    "title": "Fascination",
    "artist": "Alphabeat",
    "year": "2008"
  },
  {
    "uri": "spotify:track:6zsk6uF3MxfIeHPlubKBvR",
    "title": "Get Ur Freak On",
    "artist": "Missy Elliott",
    "year": "2001"
  },
  {
    "uri": "spotify:track:7dwJqwTXDtsrX1QLqb0o96",
    "title": "What A Man",
    "artist": "Linda Lyndell",
    "year": "1993"
  },
  {
    "uri": "spotify:track:6D7LONZbBvyremCeh8Mj2b",
    "title": "Ta' med ud å fisk - 2006 - Remaster",
    "artist": "Gitte Hænning",
    "year": "2011"
  },
  {
    "uri": "spotify:track:4rvT5iZVOCJeXZrDvy6JFK",
    "title": "What Can I Do",
    "artist": "The Corrs, Tin Tin Out",
    "year": "1998"
  },
  {
    "uri": "spotify:track:3YKptz29AsOlm7WAVnztBh",
    "title": "Kiss from a Rose",
    "artist": "Seal",
    "year": "1994"
  },
  {
    "uri": "spotify:track:7675gjlUZzneYiMrQ9Inx8",
    "title": "Mama Said",
    "artist": "Lukas Graham",
    "year": "2015"
  },
  {
    "uri": "spotify:track:6RUKPb4LETWmmr3iAEQktW",
    "title": "Something Just Like This",
    "artist": "The Chainsmokers, Coldplay",
    "year": "2017"
  },
  {
    "uri": "spotify:track:2NBQmPrOEEjA8VbeWOQGxO",
    "title": "Drop It Like It's Hot",
    "artist": "Snoop Dogg, Pharrell Williams",
    "year": "2004"
  },
  {
    "uri": "spotify:track:269y1Vw3O0C9uI3drXpfo9",
    "title": "Only Teardrops",
    "artist": "Emmelie de Forest",
    "year": "2013"
  },
  {
    "uri": "spotify:track:3LMlFQkPq3LvoCyATVu0Fq",
    "title": "Rocket Brothers",
    "artist": "Kashmir",
    "year": "2003"
  },
  {
    "uri": "spotify:track:4WxU1gDVmoH6gstgR0MT78",
    "title": "Lean On",
    "artist": "Major Lazer, DJ Snake, MØ",
    "year": "2015"
  },
  {
    "uri": "spotify:track:721DwsHOeKf7zHRABCR2rh",
    "title": "You're the Voice",
    "artist": "John Farnham",
    "year": "1986"
  },
  {
    "uri": "spotify:track:3dkIE8P7hvl3tHl9KSb6dA",
    "title": "Non, je ne regrette rien",
    "artist": "Édith Piaf",
    "year": "1987"
  },
  {
    "uri": "spotify:track:7FkyQsWH9mmxoYLCNj4f8y",
    "title": "Fire Water Burn",
    "artist": "Bloodhound Gang",
    "year": "1996"
  },
  {
    "uri": "spotify:track:05yiiw2F3XXoighyveZTDs",
    "title": "Heaven Is a Place on Earth - Promo 7\" Edit",
    "artist": "Belinda Carlisle",
    "year": "1987"
  },
  {
    "uri": "spotify:track:5qrSlOut2rNAWv3ubArkNy",
    "title": "Be Alright",
    "artist": "Dean Lewis",
    "year": "2019"
  },
  {
    "uri": "spotify:track:7g0mIr33erJ0OizHECszid",
    "title": "En Nat Bliver Det Sommer",
    "artist": "Love Shop",
    "year": "1990"
  },
  {
    "uri": "spotify:track:5YbgcwHjQhdT1BYQ4rxWlD",
    "title": "Don't Worry Be Happy",
    "artist": "Bobby McFerrin",
    "year": "1997"
  },
  {
    "uri": "spotify:track:0e7ipj03S05BNilyu5bRzt",
    "title": "rockstar (feat. 21 Savage)",
    "artist": "Post Malone, 21 Savage",
    "year": "2018"
  },
  {
    "uri": "spotify:track:2QbSGkb3TgghEHpjKCsznm",
    "title": "The Lion Sleeps Tonight (Wimoweh)",
    "artist": "The Tokens",
    "year": "1994"
  },
  {
    "uri": "spotify:track:5ZrDlcxIDZyjOzHdYW1ydr",
    "title": "Barbie Girl",
    "artist": "Aqua",
    "year": "1997"
  },
  {
    "uri": "spotify:track:0WGn8xhpPumX73lECUY5Yo",
    "title": "Everybody Get Up - Radio Edit",
    "artist": "Five",
    "year": "2001"
  },
  {
    "uri": "spotify:track:5jw1zzcYFivmuJK52JrnMK",
    "title": "Great Balls Of Fire",
    "artist": "Jerry Lee Lewis",
    "year": "1989"
  },
  {
    "uri": "spotify:track:48YTxXgK2CT31UlfYz5MKU",
    "title": "To the Moon & Back",
    "artist": "Savage Garden",
    "year": "1997"
  },
  {
    "uri": "spotify:track:3Fw35WaAh2m1GYJANUZEHl",
    "title": "Sikke'n Dejlig Dag",
    "artist": "Stig Møller",
    "year": "1994"
  },
  {
    "uri": "spotify:track:5SL8qpMk1LcECpUn2twe7N",
    "title": "Nineteenhundredandyesterday - 2009 - Remaster",
    "artist": "D-A-D",
    "year": "2000"
  },
  {
    "uri": "spotify:track:3S0OXQeoh0w6AY8WQVckRW",
    "title": "I'm Yours",
    "artist": "Jason Mraz",
    "year": "2008"
  },
  {
    "uri": "spotify:track:4DX82Vc8qAH4jJPvKxvwg6",
    "title": "Move Your Feet",
    "artist": "Junior Senior",
    "year": "2002"
  },
  {
    "uri": "spotify:track:4jh9olf0OKCokpzxSyLeJx",
    "title": "Toy Soldiers",
    "artist": "Martika",
    "year": "1988"
  },
  {
    "uri": "spotify:track:4fJyuZM1uvNQEiLMH1PQ8n",
    "title": "Kærligheden Kalder",
    "artist": "Sanne Salomonsen",
    "year": "1989"
  },
  {
    "uri": "spotify:track:5vYA1mW9g2Coh1HUFUSmlb",
    "title": "3AM",
    "artist": "Matchbox Twenty",
    "year": "1996"
  },
  {
    "uri": "spotify:track:3gWZ8TJ6oIpJWQBfrUOksW",
    "title": "Brimful of Asha - Norman Cook Remix Single Version",
    "artist": "Cornershop, Norman Cook",
    "year": "1997"
  },
  {
    "uri": "spotify:track:5jWI1xNxABzDRFTnD2yp8L",
    "title": "I Love to Love",
    "artist": "Tina Charles",
    "year": "1997"
  },
  {
    "uri": "spotify:track:7BdXRaSlGAzhySfuW3y8h5",
    "title": "She's Like the Wind (feat. Wendy Fraser) - From \"Dirty Dancing\" Soundtrack",
    "artist": "Patrick Swayze, Wendy Fraser",
    "year": "1987"
  },
  {
    "uri": "spotify:track:3BYccIpnjqBBWtr1S2EBr8",
    "title": "Mest Ondt",
    "artist": "Burhan G, Medina",
    "year": "2010"
  },
  {
    "uri": "spotify:track:2Qm5DrmotzWvqNM3JlcQYo",
    "title": "Let's Dance",
    "artist": "Chris Montez",
    "year": "1962"
  },
  {
    "uri": "spotify:track:1uzWOoJdADfstQuFtQFTUn",
    "title": "Breakfast At Tiffany's",
    "artist": "Deep Blue Something",
    "year": "1995"
  },
  {
    "uri": "spotify:track:2hKdd3qO7cWr2Jo0Bcs0MA",
    "title": "Drops of Jupiter (Tell Me)",
    "artist": "Train",
    "year": "2001"
  },
  {
    "uri": "spotify:track:0UAEHlFR79k9CJvknSGUNf",
    "title": "Pump Up The Jam - Edit",
    "artist": "Technotronic",
    "year": "2011"
  },
  {
    "uri": "spotify:track:3VgrSJEKBRT3xmwzpaxxEF",
    "title": "(Love Is Like A) Heat Wave",
    "artist": "Martha Reeves & The Vandellas",
    "year": "1963"
  },
  {
    "uri": "spotify:track:71R0DcnEd32eTWW7WOB6x6",
    "title": "Itsi-bitsi - 2015 Remastered Version",
    "artist": "Steppeulvene",
    "year": "1967"
  },
  {
    "uri": "spotify:track:6RtPijgfPKROxEzTHNRiDp",
    "title": "Rude",
    "artist": "MAGIC!",
    "year": "2014"
  },
  {
    "uri": "spotify:track:7ETXytirTgnMJzyxl4e7UI",
    "title": "Angelique",
    "artist": "Dario Campeotto",
    "year": "2002"
  },
  {
    "uri": "spotify:track:5ioHUTWy0l5ACpS7QyGwCe",
    "title": "Han Får For Lidt",
    "artist": "Østkyst Hustlers",
    "year": "1996"
  },
  {
    "uri": "spotify:track:21gZ2MetDhCPv1kNs3t9UK",
    "title": "Nitten",
    "artist": "Thomas Holm",
    "year": "2010"
  },
  {
    "uri": "spotify:track:7tnWTx0bXHI3tW5gnrbGDE",
    "title": "Indianer",
    "artist": "Tøsedrengene",
    "year": "1984"
  },
  {
    "uri": "spotify:track:7xWiCG3N7tFgPTNGVYQoq8",
    "title": "Hot!",
    "artist": "Nik & Jay",
    "year": "2003"
  },
  {
    "uri": "spotify:track:4LI7LqBRuXxLyEZ2fCQnit",
    "title": "Out of Touch",
    "artist": "Daryl Hall & John Oates",
    "year": "2001"
  },
  {
    "uri": "spotify:track:5Wtj1wQSr52bnHxnxdtTdc",
    "title": "Landet",
    "artist": "Marie Key",
    "year": "2012"
  },
  {
    "uri": "spotify:track:0GONea6G2XdnHWjNZd6zt3",
    "title": "Summer Of '69",
    "artist": "Bryan Adams",
    "year": "1984"
  },
  {
    "uri": "spotify:track:1er4mjSaS1VGfMp23rzsCV",
    "title": "Living Next Door to Alice",
    "artist": "New World",
    "year": "2020"
  },
  {
    "uri": "spotify:track:0DaOFUhUEc416QdUaW9paE",
    "title": "Absolutely Everybody",
    "artist": "Vanessa Amorosi",
    "year": "2000"
  },
  {
    "uri": "spotify:track:7sqK6f8dHVx3Q1GjFrVyGl",
    "title": "Sherry",
    "artist": "Frankie Valli & The Four Seasons",
    "year": "1962"
  },
  {
    "uri": "spotify:track:2fwfZDXNBxx2alE6clKQcZ",
    "title": "Silverflame - 2010 Digital Remaster",
    "artist": "Dizzy Mizz Lizzy",
    "year": "1994"
  },
  {
    "uri": "spotify:track:7hBGy8DIYXuUZf5ZUjKHPO",
    "title": "Kun For Mig",
    "artist": "Medina",
    "year": "2009"
  },
  {
    "uri": "spotify:track:6UPcylAJnEKnRanHyL64Qb",
    "title": "Re-sepp-ten - VM-sang 1986",
    "artist": "VM Holdet, Herrelandsholdet, Landsholdet",
    "year": "1986"
  },
  {
    "uri": "spotify:track:5IWaJGGh9FMxVe6AQO4U9A",
    "title": "Transparent and Glasslike",
    "artist": "Carpark North",
    "year": "2003"
  },
  {
    "uri": "spotify:track:37IUoAxYqcWr1VXQvmWYEZ",
    "title": "Only You (And You Alone)",
    "artist": "The Platters",
    "year": "1986"
  },
  {
    "uri": "spotify:track:1BP2TBbe9vLbGfzjxGcIXg",
    "title": "Open Wide",
    "artist": "Tina Dickow",
    "year": "2007"
  },
  {
    "uri": "spotify:track:1Qrg8KqiBpW07V7PNxwwwL",
    "title": "Kill Bill",
    "artist": "SZA",
    "year": "2022"
  },
  {
    "uri": "spotify:track:1INWPr855fwWdAOeecbu0W",
    "title": "Let's Twist Again",
    "artist": "Chubby Checker",
    "year": "1961"
  },
  {
    "uri": "spotify:track:6ZLGthToczpvnL5Eoy6yrY",
    "title": "Pure Shores",
    "artist": "All Saints",
    "year": "2000"
  },
  {
    "uri": "spotify:track:5iKAqnESRmmCrhNc6muEqq",
    "title": "Jonathan - 1995 - Remaster",
    "artist": "Back To Back",
    "year": "1995"
  },
  {
    "uri": "spotify:track:5MzphLubufqPp6GYQAjhQD",
    "title": "The Second You Sleep",
    "artist": "Saybia",
    "year": "2002"
  },
  {
    "uri": "spotify:track:09dB7Wv84s7uY40YbbeqG0",
    "title": "Dressed For Success",
    "artist": "Roxette",
    "year": "1988"
  },
  {
    "uri": "spotify:track:5G2f63n7IPVPPjfNIGih7Q",
    "title": "Taste",
    "artist": "Sabrina Carpenter",
    "year": "2024"
  },
  {
    "uri": "spotify:track:4Dvkj6JhhA12EX05fT7y2e",
    "title": "As It Was",
    "artist": "Harry Styles",
    "year": "2022"
  },
  {
    "uri": "spotify:track:29U7stRjqHU6rMiS8BfaI9",
    "title": "What A Wonderful World",
    "artist": "Louis Armstrong",
    "year": "1968"
  },
  {
    "uri": "spotify:track:34zbPJOhBLVd4sYbHSV7nr",
    "title": "Dub-I-Dub",
    "artist": "Me & My",
    "year": "1995"
  },
  {
    "uri": "spotify:track:5QDLhrAOJJdNAmCTJ8xMyW",
    "title": "Dynamite",
    "artist": "BTS",
    "year": "2020"
  },
  {
    "uri": "spotify:track:1PtQJZVZIdWIYdARpZRDFO",
    "title": "Running Up That Hill (A Deal With God)",
    "artist": "Kate Bush",
    "year": "1985"
  },
  {
    "uri": "spotify:track:1i1OuCNhNf7JwrlWlFZFu1",
    "title": "That's Not My Name",
    "artist": "The Ting Tings",
    "year": "2007"
  },
  {
    "uri": "spotify:track:5YaIqHv6K5OXngRGwkzXMO",
    "title": "Flower power tøj",
    "artist": "Ulla Pia",
    "year": "1999"
  },
  {
    "uri": "spotify:track:2iXcvnD3d1gfLBum0cE5Eg",
    "title": "Tutti Frutti",
    "artist": "Little Richard",
    "year": "1957"
  },
  {
    "uri": "spotify:track:3ia3dJETSOllPsv3LJkE35",
    "title": "California Love - Original Version",
    "artist": "2Pac, Roger, Dr. Dre",
    "year": "1998"
  },
  {
    "uri": "spotify:track:5QpaGzWp0hwB5faV8dkbAz",
    "title": "Wherever You Will Go",
    "artist": "The Calling",
    "year": "2001"
  },
  {
    "uri": "spotify:track:1Z3V1fGR5HYr232lLPVD9G",
    "title": "I Believe in a Thing Called Love - Single Version",
    "artist": "The Darkness",
    "year": "2003"
  },
  {
    "uri": "spotify:track:4rUWctsRR9xq1qujh9Pk9t",
    "title": "Elsker dig for evigt - 2003 - Remaster",
    "artist": "Lars H.U.G.",
    "year": "2004"
  },
  {
    "uri": "spotify:track:2om86fvyOE6GGtubpMkZpC",
    "title": "Gi' mig Danmark tilbage",
    "artist": "Natasja",
    "year": "2007"
  },
  {
    "uri": "spotify:track:6Nq5lE0CeOAAAqN4qhkbZU",
    "title": "Suga Suga",
    "artist": "Baby Bash, Frankie J",
    "year": "2003"
  },
  {
    "uri": "spotify:track:5f2CcxzZoW7hNs1O8NhG6y",
    "title": "When I Get Old",
    "artist": "Christopher, CHUNG HA",
    "year": "2022"
  },
  {
    "uri": "spotify:track:2qhASBzpbFhPRtrnZ5lLnz",
    "title": "Unchained Melody",
    "artist": "The Righteous Brothers",
    "year": "1965"
  },
  {
    "uri": "spotify:track:7tqhbajSfrz2F7E1Z75ASX",
    "title": "Ain't No Mountain High Enough",
    "artist": "Marvin Gaye, Tammi Terrell",
    "year": "1967"
  },
  {
    "uri": "spotify:track:1jJci4qxiYcOHhQR247rEU",
    "title": "Kids",
    "artist": "MGMT",
    "year": "2007"
  },
  {
    "uri": "spotify:track:5yGTQzYbEdY6B9RFZJypgt",
    "title": "Rhythm Of The Night",
    "artist": "DeBarge",
    "year": "1985"
  },
  {
    "uri": "spotify:track:26QKxvjlCo2fSd3T4c8Zpb",
    "title": "Heart of Gold",
    "artist": "Neil Young",
    "year": "1972"
  },
  {
    "uri": "spotify:track:0iOZM63lendWRTTeKhZBSC",
    "title": "Mrs. Robinson - From \"The Graduate\" Soundtrack",
    "artist": "Simon & Garfunkel",
    "year": "1968"
  },
  {
    "uri": "spotify:track:2HHtWyy5CgaQbC7XSoOb0e",
    "title": "Eye of the Tiger",
    "artist": "Survivor",
    "year": "1982"
  },
  {
    "uri": "spotify:track:2bHLKpSdVarDmfMZFabaBj",
    "title": "Kvinde Min",
    "artist": "Gasolin'",
    "year": "1975"
  },
  {
    "uri": "spotify:track:2EM9zpAc7PVeoAydmbfVIL",
    "title": "La Camisa Negra",
    "artist": "Juanes",
    "year": "2004"
  },
  {
    "uri": "spotify:track:0C5Ex6F2W9q1frGs0w9D0K",
    "title": "Tingelingeling For Mig - (Teatertosset)",
    "artist": "Marguerite Viby",
    "year": "1997"
  },
  {
    "uri": "spotify:track:6sLid9c6N1iJZsNx8uEuDA",
    "title": "Først en halv time på den ene side så en halv time på den anden",
    "artist": "Niels Hausgaard",
    "year": "2011"
  },
  {
    "uri": "spotify:track:1XWieuwDLdpyPBKusKFATN",
    "title": "Kender Du Det?",
    "artist": "Søren Kragh-Jacobsen, Leif Lindskov",
    "year": "1975"
  },
  {
    "uri": "spotify:track:5YLnfy7R2kueN0BRPkjiEG",
    "title": "I'll Take You There",
    "artist": "The Staple Singers",
    "year": "2007"
  },
  {
    "uri": "spotify:track:2FQrifJ1N335Ljm3TjTVVf",
    "title": "A Bar Song (Tipsy)",
    "artist": "Shaboozey",
    "year": "2024"
  },
  {
    "uri": "spotify:track:60G0YTBb4gtAgb0ODAPNAn",
    "title": "What A Life",
    "artist": "Scarlet Pleasure",
    "year": "2019"
  },
  {
    "uri": "spotify:track:5CQ30WqJwcep0pYcV4AMNc",
    "title": "Stairway to Heaven - Remaster",
    "artist": "Led Zeppelin",
    "year": "1971"
  },
  {
    "uri": "spotify:track:0D2VYiRlBv43asKUgieZaM",
    "title": "Jubel - Radio Edit",
    "artist": "Klingande",
    "year": "2013"
  },
  {
    "uri": "spotify:track:66PsWt1kmbGog4rw2kNdmh",
    "title": "Midsommersangen",
    "artist": "Shu-Bi-Dua",
    "year": "2010"
  },
  {
    "uri": "spotify:track:6aX8bwbEzlhOh3bN6rLw5p",
    "title": "Hun Vil Ha' En Rapper",
    "artist": "Jooks",
    "year": "2009"
  },
  {
    "uri": "spotify:track:59VRFpPnC8pOhIH2WCWXF9",
    "title": "Saturday Night - Radio Mix",
    "artist": "Whigfield",
    "year": "1994"
  },
  {
    "uri": "spotify:track:3LaHsdzzmvhx6TJedpomVy",
    "title": "Kids In America",
    "artist": "Kim Wilde",
    "year": "1981"
  },
  {
    "uri": "spotify:track:0V3wPSX9ygBnCm8psDIegu",
    "title": "Anti-Hero",
    "artist": "Taylor Swift",
    "year": "2022"
  },
  {
    "uri": "spotify:track:7eJMfftS33KTjuF7lTsMCx",
    "title": "death bed (coffee for your head)",
    "artist": "Powfu, beabadoobee",
    "year": "2020"
  },
  {
    "uri": "spotify:track:3LlqJkcXMBIAE5X1uUiZUN",
    "title": "Under Din Sne",
    "artist": "The Minds Of 99",
    "year": "2022"
  },
  {
    "uri": "spotify:track:7w87IxuO7BDcJ3YUqCyMTT",
    "title": "Pumped Up Kicks",
    "artist": "Foster The People",
    "year": "2011"
  },
  {
    "uri": "spotify:track:3dYD57lRAUcMHufyqn9GcI",
    "title": "Take Me To Church",
    "artist": "Hozier",
    "year": "2014"
  },
  {
    "uri": "spotify:track:2eBUJHZpPmYIpeYpV6Fko1",
    "title": "Jeg snakker med mig selv",
    "artist": "Gitte Hænning",
    "year": "1986"
  },
  {
    "uri": "spotify:track:1lkvpmrCaXK8QtliFDcHBO",
    "title": "Bubbly",
    "artist": "Colbie Caillat",
    "year": "2007"
  },
  {
    "uri": "spotify:track:1QbOvACeYanja5pbnJbAmk",
    "title": "Take Me Home, Country Roads",
    "artist": "John Denver",
    "year": "1997"
  },
  {
    "uri": "spotify:track:7o7E1nrHWncYY7PY94gCiX",
    "title": "Video Killed The Radio Star",
    "artist": "The Buggles",
    "year": "1980"
  },
  {
    "uri": "spotify:track:7mze3mJmu79AJu8SnS37pS",
    "title": "Aicha",
    "artist": "Outlandish",
    "year": "2003"
  },
  {
    "uri": "spotify:track:5X79VgaOn8pDTpTKu3PixN",
    "title": "We're Not Gonna Take It",
    "artist": "Twisted Sister",
    "year": "1984"
  },
  {
    "uri": "spotify:track:6EeFWOXlqtjhFQMmeqb295",
    "title": "I Wanna Be Dancing",
    "artist": "Drew Sycamore",
    "year": "2021"
  },
  {
    "uri": "spotify:track:2PzU4IB8Dr6mxV3lHuaG34",
    "title": "(I Can't Get No) Satisfaction - Mono",
    "artist": "The Rolling Stones",
    "year": "1965"
  },
  {
    "uri": "spotify:track:4Hhv2vrOTy89HFRcjU3QOx",
    "title": "At Last",
    "artist": "Etta James",
    "year": "1960"
  },
  {
    "uri": "spotify:track:3BBrzuiikUPp2eT66nGDKJ",
    "title": "Smuk Og Dejlig",
    "artist": "Shit & Chalou",
    "year": "1976"
  },
  {
    "uri": "spotify:track:2aNYsrhYjhjo62oY0lSjIe",
    "title": "Vi skal gå hånd i hånd",
    "artist": "Keld Heick, The Donkeys",
    "year": "2014"
  },
  {
    "uri": "spotify:track:4k4CxTNX06nNJTqPGr0n8Q",
    "title": "Rør ved mig",
    "artist": "Lecia & Lucienne",
    "year": "1998"
  },
  {
    "uri": "spotify:track:4CNL4GBNTdVIU5Nk6hB4LC",
    "title": "Brown Eyed Girl",
    "artist": "Van Morrison",
    "year": "1967"
  },
  {
    "uri": "spotify:track:03UrZgTINDqvnUMbbIMhql",
    "title": "Gangnam Style (강남스타일)",
    "artist": "PSY",
    "year": "2012"
  }
];
