// Auto-generated by scripts/fetch-playlist.mjs
// 0 tracks from Hitster playlist
// NOTE: Spotify API returned 403 Forbidden for playlist tracks endpoint.
// The Spotify app (client ID 39874386f62845a792cd7dbbea3e6fb7) needs Extended Quota Mode
// approval in the Spotify Developer Dashboard to access playlist track listings.
// Re-run: node scripts/fetch-playlist.mjs <CLIENT_ID> <CLIENT_SECRET> <PLAYLIST_ID> > tracks.js
const TRACKS = [];
