// Reads hitster-denmark-playlist.md, searches Spotify for each track,
// and writes tracks.js with uri + title + artist + year.
// Usage: node scripts/build-tracks.mjs <CLIENT_ID> <CLIENT_SECRET>

const [,, CLIENT_ID, CLIENT_SECRET] = process.argv;

if (!CLIENT_ID || !CLIENT_SECRET) {
  console.error('Usage: node scripts/build-tracks.mjs <CLIENT_ID> <CLIENT_SECRET>');
  process.exit(1);
}

import { readFileSync } from 'fs';

// ── Parse markdown table ──────────────────────────────────────────────────────

function parseMarkdown(md) {
  return md.split('\n')
    .filter(line => /^\|\s*\d+\s*\|/.test(line))
    .map(line => {
      const cols = line.split('|').map(c => c.trim()).filter(Boolean);
      return { title: cols[1], artist: cols[2] };
    });
}

// ── Spotify auth ──────────────────────────────────────────────────────────────

async function getToken() {
  const res = await fetch('https://accounts.spotify.com/api/token', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/x-www-form-urlencoded',
      'Authorization': 'Basic ' + Buffer.from(`${CLIENT_ID}:${CLIENT_SECRET}`).toString('base64'),
    },
    body: 'grant_type=client_credentials',
  });
  const data = await res.json();
  if (!data.access_token) throw new Error('Auth failed: ' + JSON.stringify(data));
  return data.access_token;
}

// ── Search for one track ──────────────────────────────────────────────────────

async function searchTrack(token, title, artist) {
  // Strip remaster/version notes from title for cleaner search
  const cleanTitle = title.replace(/\s*[-–]\s*(remaster(ed)?|remix|radio edit|single edit|original version|mono|live|full length version|\d{4}( -(digital )?remaster)?)[^|]*/gi, '').trim();
  const q = encodeURIComponent(`track:${cleanTitle} artist:${artist}`);
  const res = await fetch(
    `https://api.spotify.com/v1/search?q=${q}&type=track&limit=1&market=DK`,
    { headers: { Authorization: `Bearer ${token}` } }
  );
  const data = await res.json();
  if (data.error) return null;
  const item = data.tracks?.items?.[0];
  if (!item) return null;
  return {
    uri: item.uri,
    title: item.name,
    artist: item.artists.map(a => a.name).join(', '),
    year: item.album.release_date.slice(0, 4),
  };
}

function sleep(ms) { return new Promise(r => setTimeout(r, ms)); }

// ── Main ──────────────────────────────────────────────────────────────────────

const md = readFileSync('hitster-denmark-playlist.md', 'utf8');
const songs = parseMarkdown(md);
console.error(`Parsed ${songs.length} songs from markdown`);

const token = await getToken();
console.error('Got Spotify token');

const tracks = [];
const failed = [];

for (let i = 0; i < songs.length; i++) {
  const { title, artist } = songs[i];
  process.stderr.write(`[${i + 1}/${songs.length}] ${title} – ${artist} ... `);

  try {
    const track = await searchTrack(token, title, artist);
    if (track) {
      tracks.push(track);
      process.stderr.write(`✓ ${track.year}\n`);
    } else {
      failed.push({ title, artist });
      process.stderr.write(`✗ not found\n`);
    }
  } catch (e) {
    failed.push({ title, artist });
    process.stderr.write(`✗ error: ${e.message}\n`);
  }

  // Avoid Spotify rate limiting (429)
  await sleep(150);
}

if (failed.length > 0) {
  console.error(`\n⚠ ${failed.length} tracks not found:`);
  failed.forEach(t => console.error(`  - ${t.title} – ${t.artist}`));
}

const output = `// Auto-generated by scripts/build-tracks.mjs\n// ${tracks.length} tracks from HITSTER Denmark playlist\nconst TRACKS = ${JSON.stringify(tracks, null, 2)};\n`;
process.stdout.write(output);
console.error(`\n✓ Done: ${tracks.length} tracks written`);
